# Stage 1: Build the application
FROM gradle:7.6.0-jdk17 AS build
WORKDIR /app

RUN git clone https://github.com/ORT-Taller-ATI/deploy-apps-ejemplos.git
WORKDIR /app/deploy-apps-ejemplos/SpringBoot-web-form
RUN gradle clean build -x test

FROM openjdk:17-jdk-slim
WORKDIR /app

COPY --from=build /app/deploy-apps-ejemplos/SpringBoot-web-form/build/libs/webapp-0.0.1-SNAPSHOT.jar webapp.jar
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "webapp.jar"]